"""add_ai_prompt_columns

Revision ID: 51ef90c15388
Revises: 7c819eed91ce
Create Date: 2026-04-09 15:04:08.199570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51ef90c15388'
down_revision = '7c819eed91ce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_config', sa.Column('summarize_prompt', sa.Text(), nullable=True))
    op.add_column('system_config', sa.Column('translate_prompt', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_config', 'translate_prompt')
    op.drop_column('system_config', 'summarize_prompt')
    # ### end Alembic commands ###
