"""add updated_at column to sources table

Revision ID: 6893d5c420b6
Revises: 
Create Date: 2026-02-23 15:02:39.462417

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6893d5c420b6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('contents', 'quality_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('contents', 'processed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('contents', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True,
               existing_server_default=sa.text("'pending'::text"))
    op.drop_index('idx_contents_original_url', table_name='contents')
    op.create_index(op.f('ix_contents_original_url'), 'contents', ['original_url'], unique=True)
    op.add_column('send_logs', sa.Column('success', sa.Boolean(), nullable=True))
    op.alter_column('send_logs', 'channel_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('send_logs', 'sent_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('send_logs', 'content_id')
    op.drop_column('send_logs', 'status')
    op.add_column('sources', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('sources', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('sources', 'type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('sources', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('sources', 'max_items_per_run',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('3'))
    op.alter_column('sources', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_sources_url', table_name='sources')
    op.create_index(op.f('ix_sources_url'), 'sources', ['url'], unique=True)
    op.add_column('subscribers', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('subscribers', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('subscribers', 'identifier',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('subscribers', 'channel_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('subscribers', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('subscribers', 'preferences',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.create_index(op.f('ix_subscribers_identifier'), 'subscribers', ['identifier'], unique=True)
    op.drop_column('subscribers', 'subscribed_at')
    op.drop_column('subscribers', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribers', sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('subscribers', sa.Column('subscribed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_subscribers_identifier'), table_name='subscribers')
    op.alter_column('subscribers', 'preferences',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('subscribers', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('subscribers', 'channel_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('subscribers', 'identifier',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('subscribers', 'updated_at')
    op.drop_column('subscribers', 'created_at')
    op.drop_index(op.f('ix_sources_url'), table_name='sources')
    op.create_index('idx_sources_url', 'sources', ['url'], unique=True)
    op.alter_column('sources', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('sources', 'max_items_per_run',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('3'))
    op.alter_column('sources', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('sources', 'type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('sources', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('sources', 'updated_at')
    op.add_column('send_logs', sa.Column('status', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('send_logs', sa.Column('content_id', sa.UUID(), autoincrement=False, nullable=False))
    op.alter_column('send_logs', 'sent_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('send_logs', 'channel_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('send_logs', 'success')
    op.drop_index(op.f('ix_contents_original_url'), table_name='contents')
    op.create_index('idx_contents_original_url', 'contents', ['original_url'], unique=True)
    op.alter_column('contents', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'pending'::text"))
    op.alter_column('contents', 'processed_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('contents', 'quality_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_column('contents', 'created_at')
    # ### end Alembic commands ###
