"""add_system_config_and_fk_constraints

Revision ID: 7c819eed91ce
Revises: 6893d5c420b6
Create Date: 2026-03-28 08:25:59.513200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c819eed91ce'
down_revision = '6893d5c420b6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weekly_cron', sa.String(), nullable=False),
    sa.Column('ai_model', sa.String(), nullable=False),
    sa.Column('default_max_items_per_run', sa.Integer(), nullable=False),
    sa.Column('force_recent', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(
        'fk_contents_source_id', 'contents', 'sources', ['source_id'], ['id'], ondelete='RESTRICT'
    )
    op.create_foreign_key(
        'fk_send_logs_subscriber_id', 'send_logs', 'subscribers', ['subscriber_id'], ['id'], ondelete='RESTRICT'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_send_logs_subscriber_id', 'send_logs', type_='foreignkey')
    op.drop_constraint('fk_contents_source_id', 'contents', type_='foreignkey')
    op.drop_table('system_config')
    # ### end Alembic commands ###
